# Numerical Python (Numpy)

NumPy (Numerical Python) is a powerful Python library built on C, acting as a wrapper around C functions to leverage its superior execution speed. Numpy improves Python language capabilities to operate with multidimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

Unlike standard Python lists—which are flexible arrays containing pointers to objects scattered in memory—NumPy arrays consist of fixed-type data (such as continuous blocks of 32-bit integers).

This architecture allows NumPy to process operations much faster than Python lists for three key reasons:

- Uniform Data Types: Because all elements share the exact same data type, operations can be executed directly without constant type-checking.

- Reduced Overhead: Standard Python list items must store size, reference counts, object types, and values individually. NumPy's streamlined structure eliminates this overhead, resulting in significantly faster processing and lower memory consumption.

- Contiguous Memory Allocation: NumPy stores its data in continuous blocks right next to each other in memory. In contrast, standard Python lists scatter items across memory, forcing the CPU to waste time jumping back and forth to retrieve them. Continuous memory allows for much faster data access and better utilization of modern CPU caching.

Therefore, we can conclude that *Python Lists* are designed for general-purpose programming and data organization. They support operations like appending, inserting, and removing items easily, but do not support native mathematical operations (e.g., adding two lists together concatenates them rather than adding their elements mathematically), while *NumPy Arrays* are designed specifically for mathematical and numerical computations. They natively support vectorized math, matrix multiplications, linear algebra, statistical operations, and broadcasting.

Other libraries like Tensorflow or Scipy are built on Numpy. It worth the time!

### Content
- 1. BASIC OPERATIONS
    - 1.1. Creating arrays
    - 1.2. Methods and important properties
    - 1.3. Modifying the datatype
    - 1.4. Trigonometric functions
    - 1.5. Operating with arrays
    - 1.6. Generating random numbers
    - 1.7. Obtaining statistics 
    - 1.8. Filtering data
    - 1.9. Concatenating arrays
    - 1.10. Selecting data inside arrays
- 2. LINEAR ALGEBRA
    - 2.1. Eigenvalues and Eigenvectors 
    - 2.2. Solving linear systems
- 3. LOADING DATA INTO NUMPY
    - 3.1. Loading data using CSVs

## 1. BASIC OPERATIONS
## 1.1. Creating arrays.
The arrays are the core elements of Numpy. The first step is loading Numpy:

In [64]:
# First install Numpy as pip install numpy
import numpy as np

In [65]:
# list are created as follows
list1 = [1, 2, 3, 4, 5]

In [66]:
# We can create a numpy array from the list already created or directly introducing the values in the array as follows
arr1 =np.array(list1)
arr2 = np.array([30, 21, 8, 14, 5])

In [67]:
#To retreive the array we can use the print function as follows
print(arr1)
print(arr2)

[1 2 3 4 5]
[30 21  8 14  5]


Please notice the difference between lists and arrays when presented 

In [68]:
print("A list is: ", list1, "and a numpy array is: ", arr1)

A list is:  [1, 2, 3, 4, 5] and a numpy array is:  [1 2 3 4 5]


An array may be or higher order (n-dimentional). Hence, These arrays can be created as:

In [69]:
arr_2d = np.array([[24,14,7],[51,3,95]])

arr_2d 

array([[24, 14,  7],
       [51,  3, 95]])

In [70]:
# We can create empty matrices with zeros or ones as follows
arr_zeros = np.zeros((3, 4)) # 3 rows and 4 columns
arr_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [71]:
# A matix full of ones is useful too
arr_ones = np.ones((2, 3)) # 2 rows and 3 columns
arr_ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [72]:
# A unidimensional array can be created with the arange function as follows
arr_range = np.arange(0, 60, 2) # from 0 to 59 with a step of 2
arr_range

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [73]:
# A controled array can be created with the linspace function as follows
arr_linspace = np.linspace(0, 5, 10) # A unidimensional array from 0 to 5 with 10 evenly spaced values
arr_linspace

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

## 1.2. Methods and important properties
The most basic properties of arrays are

In [74]:
# The shape of an array can be retrieved using the shape attribute as follows
arr_2d.shape 

(2, 3)

Indicates the number of rows and columns in the array. In this case, it is a 2x3 array (2 rows and 3 columns).

In [75]:
# The number of dimensions of an array can be retrieved using the ndim attribute as follows
arr_2d.ndim

2

The dimensions indicates the number of axes or the rank of the array. In the precedent example, 2 dimensions.

In [76]:
# The data type of an array can be retrieved using the dtype attribute as follows
arr_2d.dtype

dtype('int32')

This means integer of 32 bits. The data type indicates the size of memory used in computers memory for each element. 

In [77]:
# The number of elements in and array can be retrieved using the size attribute as follows
arr_2d.size

6

In [78]:
# A matrix with can be changed of size with the reshape function as follows
arr_reshaped = arr_range.reshape(3, 10) # reshape to 3 rows and 10 columns
arr_reshaped

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58]])

## 1.3. Modifying the datatype

In [79]:
# At the moment of creation
arr_3d = np.array([
    [[1, 2, 3], [4, 5, 6]], 
    [[7, 8, 9], [10, 11, 12]]
    ], dtype=np.int16)

In [80]:
# Now the type of the array is not int32 (the difault) but int16, which is a smaller data type that uses less memory. 
# This can be useful when working with large datasets or when memory usage is a concern.
arr_3d


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int16)

Be careful with n-dimension arrays. 3d-arrays are built with ("# blocks", "# rows", "# columns")

In [81]:
arr_3d.shape

(2, 2, 3)

In [82]:
arr_3d.ndim

3

In [83]:
# Or Convert to float and already created array
arr2_float = arr2.astype(float) # or np.float64
arr2_float

array([30., 21.,  8., 14.,  5.])

## 1.4. Trigonometric functions

In [84]:
# trigonometric functions can be applied to arrays as follows 
from numpy import sin, cos, pi

radians = np.linspace(0, 2*pi, 100) # 100 evenly spaced values from 0 to 2*pi
radians

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [85]:
# sine and Cosine functions can be simply applied to the array as
sine = sin(radians)
cosine = cos(radians)

# Sine values are:
print("Sine values: ", sine)

Sine values:  [ 0.00000000e+00  6.34239197e-02  1.26592454e-01  1.89251244e-01
  2.51147987e-01  3.12033446e-01  3.71662456e-01  4.29794912e-01
  4.86196736e-01  5.40640817e-01  5.92907929e-01  6.42787610e-01
  6.90079011e-01  7.34591709e-01  7.76146464e-01  8.14575952e-01
  8.49725430e-01  8.81453363e-01  9.09631995e-01  9.34147860e-01
  9.54902241e-01  9.71811568e-01  9.84807753e-01  9.93838464e-01
  9.98867339e-01  9.99874128e-01  9.96854776e-01  9.89821442e-01
  9.78802446e-01  9.63842159e-01  9.45000819e-01  9.22354294e-01
  8.95993774e-01  8.66025404e-01  8.32569855e-01  7.95761841e-01
  7.55749574e-01  7.12694171e-01  6.66769001e-01  6.18158986e-01
  5.67059864e-01  5.13677392e-01  4.58226522e-01  4.00930535e-01
  3.42020143e-01  2.81732557e-01  2.20310533e-01  1.58001396e-01
  9.50560433e-02  3.17279335e-02 -3.17279335e-02 -9.50560433e-02
 -1.58001396e-01 -2.20310533e-01 -2.81732557e-01 -3.42020143e-01
 -4.00930535e-01 -4.58226522e-01 -5.13677392e-01 -5.67059864e-01
 -6.1815898

## 1.5. Operations with arrays

Multiple operations can be performed in a simple way. 

In [86]:
# Recall arr1 and arr2 are 1D arrays, we can perform element-wise operations on them as follows
print("Recall arr1 and arr2 are 1D arrays:")
print("Array 1: ", arr1)
print("Array 2: ", arr2)

Recall arr1 and arr2 are 1D arrays:
Array 1:  [1 2 3 4 5]
Array 2:  [30 21  8 14  5]


In [87]:
print("we can perform element-wise operations on them as follows:")
sum_arr = arr1 + arr2 # It adds ith element of arr1 to ith element of arr2
diff_arr = arr1 - arr2 # it subtracts ith element of arr2 from ith element of arr1
prod_arr = arr1 * arr2 # it performs the dot product of the two arrays, multiplying ith element of arr1 by ith element of arr2
quot_arr = arr1 / arr2 # it divides ith element of arr1 by ith element of arr2

print("Sum: ", sum_arr)
print("Difference: ", diff_arr)
print("Product: ", prod_arr)
print("Quotient: ", quot_arr)

we can perform element-wise operations on them as follows:
Sum:  [31 23 11 18 10]
Difference:  [-29 -19  -5 -10   0]
Product:  [30 42 24 56 25]
Quotient:  [0.03333333 0.0952381  0.375      0.28571429 1.        ]


Concatenation of arrays is highly used, it can be done as

In [88]:
# Concatenation of arrays can be done using the concatenate function as follows
concatenated_arr = np.concatenate([arr1, arr2]) # This created a whole new array 
print("Concatenated Array: ", concatenated_arr)

Concatenated Array:  [ 1  2  3  4  5 30 21  8 14  5]


In [89]:
# organizing the elements of an array can be done using the sort function as follows
sorted_array = np.sort(concatenated_arr) # This sorts the array in ascending order
print("Sorted Concatenated Array: ", sorted_array)

Sorted Concatenated Array:  [ 1  2  3  4  5  5  8 14 21 30]


## 1.6. Generating random numbers

Random values are important to validate hypothesis and many more.

In [90]:
# Random numbers can be generated using the random module of numpy as follows
rg = np.random.default_rng(2) # Create a random number generator anchored in the seed of 2
# Using the same seed ensured obtaining the same random numbers each time the code is run, 
# which is useful for reproducibility in experiments and testing.


In [91]:
# our random object rg is used to generate the random numbers as follows
random = rg.random(1000) # Create an array of 1000 random numbers between 0 and 1 using the archored seed of 2
random

array([0.26161213, 0.29849114, 0.81422574, 0.09191594, 0.60010053,
       0.72856053, 0.18790107, 0.05514663, 0.27496937, 0.65743301,
       0.56226566, 0.15006226, 0.43263079, 0.6692973 , 0.42278467,
       0.6331844 , 0.96743595, 0.68306482, 0.39162483, 0.18725257,
       0.34596067, 0.51106597, 0.89120941, 0.77556394, 0.3181466 ,
       0.9242169 , 0.47090989, 0.69375884, 0.10720731, 0.10454356,
       0.20190745, 0.88444967, 0.67981146, 0.84923632, 0.64443627,
       0.4065424 , 0.51657819, 0.59344352, 0.86211798, 0.43818617,
       0.89224011, 0.61371694, 0.82935613, 0.49805605, 0.69251813,
       0.33902537, 0.5228285 , 0.21622339, 0.1007036 , 0.03860413,
       0.70194948, 0.45643062, 0.89773415, 0.8351832 , 0.38509513,
       0.97367877, 0.59206201, 0.76588331, 0.40719436, 0.19616991,
       0.17177702, 0.18120623, 0.60380552, 0.11263286, 0.01991075,
       0.83299696, 0.09941112, 0.45058454, 0.48849857, 0.62027241,
       0.50401448, 0.93734314, 0.75039659, 0.5744665 , 0.61727

In [92]:
# Random data from a normal distribution can be generated using the normal function as follows
random_normal = rg.normal(10, 5, 100000) # 10000 random numbers with a mean of 10 and a standard deviation of 5
random_normal

array([13.51638928, 14.60947682,  6.23501862, ...,  3.56636798,
        8.66660197, 12.61968552])

In [93]:
# An array of integers can be generated using the integers function as follows
integers = rg.integers(0, 100, 2000) # 2000 random integers between 0 and 100
integers

array([85, 47, 30, ..., 80, 74, 47], dtype=int64)

## 1.7. Statistics from arrays

In [94]:
# minimum and maximum values of an array can be retrieved using the min and max functions as follows
integers.min()

0

In [95]:
integers.max()

99

In [96]:
integers.mean()

49.3175

In [97]:
integers.std()

29.192373897132793

In [98]:
integers.var()

852.1946937499999

In [99]:
integers.sum()

98635

The same functions apply to n-dimensional arrays

In [100]:
# The minimum value of each colum is calculated as
arr_2d.min(axis=0) # axis=0 means we are looking for the minimum value of each column

array([24,  3,  7])

In [101]:
# The maximum value of each column is calculated as
arr_2d.max(axis=1) # axis=1 means we are looking for the maximum value of each row

array([24, 95])

## 1.8. Filtering data 

In [102]:
# To get information that satisfy conditions we use filters in the form "array (operator) condition"
arr_2d < 12

array([[False, False,  True],
       [False,  True, False]])

In [103]:
# Filter the array to get elements less than 12 the general form of array[filter] is applied
arr_2d[arr_2d < 12]

array([7, 3])

Be carefull that the array is reshaped.

## 1.9. Concatenating arrays

In [104]:
# Knowing that we can create two random arrays of integers as follows
np1 = rg.integers(20, size=(3,3))
np2 = rg.integers(20, size=(3,3))

print("Array 1: \n", np1)
print("Array 2: \n", np2)   

Array 1: 
 [[11  2  8]
 [ 8  6  4]
 [16  0  8]]
Array 2: 
 [[10 10 13]
 [15 10  2]
 [17  4 13]]


In [105]:
# we concatenate arrays using the concatenate function as follows
arr_concatenated_h = np.concatenate([np1, np2], axis=1) # This created a whole new array adding the columns of np2 to the columns of np1
arr_concatenated_h

array([[11,  2,  8, 10, 10, 13],
       [ 8,  6,  4, 15, 10,  2],
       [16,  0,  8, 17,  4, 13]], dtype=int64)

In [106]:
arr_concatenated_v = np.concatenate([np1, np2], axis=0) # This created a whole new array adding the rows of np2 to the rows of np1
arr_concatenated_v

array([[11,  2,  8],
       [ 8,  6,  4],
       [16,  0,  8],
       [10, 10, 13],
       [15, 10,  2],
       [17,  4, 13]], dtype=int64)

In [107]:
# Another way to concatenate arrays is using the stack function as follows
arr_stacked = np.stack([np1, np2], axis=0) # This created a whole new array stacking the arrays along a new axis
arr_stacked

array([[[11,  2,  8],
        [ 8,  6,  4],
        [16,  0,  8]],

       [[10, 10, 13],
        [15, 10,  2],
        [17,  4, 13]]], dtype=int64)

In [108]:
arr_stacked.ndim

3

## 1.10.  Selecting data inside arrays

These methods are used intensively in neural network operations

In [109]:
# Python used zero as starting point of indexing, so the first array of the stacked array can be retrieved as follows
arr_stacked[0:1] #This takes the first array of the stacked array, which is the same as np1. 
# The result is a 3D array with shape (1, 3, 3).

array([[[11,  2,  8],
        [ 8,  6,  4],
        [16,  0,  8]]], dtype=int64)

In [112]:
integers[0:5] # This returns the first 5 elements of the integers array, 
# which is a 1D array with shape (5,).

array([85, 47, 30, 16, 93], dtype=int64)

In [113]:
integers[0:20:2] # This returns every second element of the first 20 elements of the integers array, 
# which is a 1D array with shape (10,).

array([85, 30, 93,  4, 47, 49, 79, 12,  3,  1], dtype=int64)

In [114]:
# All the elements in even positions are retrieved as follows
integers[::2]

array([85, 30, 93,  4, 47, 49, 79, 12,  3,  1,  1, 59, 53, 92, 43, 66, 92,
       30, 45, 82, 34, 17, 61, 13, 88, 68, 82, 21, 36,  0, 11, 18, 15, 34,
       12, 35, 69, 13, 70, 88, 53, 18, 96, 35, 86, 26, 35, 46, 15, 48, 11,
       70, 87,  1, 30,  5, 50, 28,  5, 94, 91, 76, 83, 46,  4, 61, 96, 11,
       61, 40,  7, 47, 29, 46, 54, 10, 97,  0, 87, 15, 17, 83, 69,  8, 44,
       89, 68, 53, 93, 44, 75, 41, 83, 21, 42, 52, 85, 62, 65,  0, 33, 96,
       13, 90, 60, 91, 93, 47, 99, 66, 28, 51, 47,  2, 34, 23, 33, 38,  3,
       89, 93, 81, 56, 33, 17, 52, 77, 51, 81, 55, 78, 25, 51, 81,  5, 81,
        1, 71, 98, 57, 11,  0, 39, 21, 70, 15, 61, 65, 59, 26, 99, 13,  9,
       59, 26, 40,  1, 34,  0, 71, 52, 21, 80, 36,  6, 31, 54, 26, 93, 54,
       24, 14, 68, 79, 61, 34, 27,  3, 87, 78, 59, 35, 49, 68, 16, 47, 20,
        0,  8, 13, 69, 32, 34,  1, 89, 62, 53, 72, 99,  3,  5, 15, 65, 51,
       29, 28, 10, 15, 49,  6, 11, 88, 77, 45, 96, 27, 87, 52, 81, 69, 75,
       96, 27, 54, 94, 84

To individualize an element we use the structure array[#row, #col] 

In [117]:
# Using this array
integers_2d = rg.integers(20, size=(8, 5)) # Create a 2D array of random integers between 0 and 20 with shape (8, 5)
integers_2d

array([[ 1,  8, 17, 17, 16],
       [ 1, 15,  1, 13,  4],
       [ 5,  5, 16,  0,  4],
       [ 7,  3, 16, 14, 19],
       [ 9, 14,  6, 16,  0],
       [15, 11,  3, 10, 18],
       [ 3, 13,  5, 10, 11],
       [16,  1,  1, 19,  3]], dtype=int64)

In [118]:
integers_2d[3,4] # This returns the element in the 4th row and 5th column of the integers_2d array,

19

__In Numpy the upper limit for slicing is never included__

In [120]:
# To return the second value of the 3th, 4th and 5th rows of the 2D array, we can use slicing as follows
integers_2d[2:5,1] 

array([ 5,  3, 14], dtype=int64)

In [ ]:
# to return the first pair of elements of the last 3 rows of the 2D array, we can use slicing as follows
integers_2d[-3:, 0:2] 

array([[15, 11],
       [ 3, 13],
       [16,  1]], dtype=int64)

## 2. LINEAR ALGEBRA

## 2.1. Eigenvalues and Eigenvector

Eigenvalues and eigenvectors are special numbers and vectors associated with linear transformations, defined by the fundamental equation Av = λ v, where A is a matrix, v is the eigenvector, and λ is the eigenvalue.

- An __Eigenvector (v)__ is a non-zero vector that does not change direction when a linear transformation (matrix multiplication) is applied to it; it only changes by a scaling factor. 

- An __Eigenvalue (λ)__ is the scalar factor by which the corresponding eigenvector is scaled (stretched, compressed, or reversed) during the transformation.

Straight eigenvalues and eigenvectors decomposition can be applied to squared matrices only. For non-squared matrices, ither methods such as Singular Value Decomposition (SVD) should be used.

Their principal uses are simplifying powers of matrices and systems of differential equations (Matrix diagonalization), reducing data dimensions using tools like Principal Component Analysis (PCA), and pawering Algorithms such as *power ranking* in search engines like Google's PageRank. Know more [here](https://math.mit.edu/~gs/linearalgebra/ila5/linearalgebra5_6-1.pdf)

In [128]:
# Take an squared 2d array of random integers between 0 and 20 with shape (4, 4)
s_2d_array = rg.integers(20, size=(4, 4)) 
s_2d_array

array([[ 6, 17,  3,  2],
       [ 2, 13,  6, 19],
       [ 0,  9,  5, 18],
       [ 7,  9,  5,  2]], dtype=int64)

In [136]:
#  The decomposition in eigenvalues and eigenvectors of a square matrix can be computed using the linalg.eig function as follows
eigenvalues, eigenvectors = np.linalg.eig(s_2d_array)

# The eigenvalues is a column vectorwith the eigenvalues of the matrix
print("Eigenvalues: \n", eigenvalues)


Eigenvalues: 
 [31.31517906+0.j        -2.90429416+4.3447521j -2.90429416-4.3447521j
  0.49340927+0.j       ]


In [137]:
# The eigenvectors is a matrix with the corresponding eigenvectors as columns. 
print("Eigenvectors: \n", eigenvectors)
 

Eigenvectors: 
 [[-0.49837648+0.j          0.68738849+0.j          0.68738849-0.j
  -0.60525749+0.j        ]
 [-0.61266051+0.j         -0.31969143+0.16901649j -0.31969143-0.16901649j
   0.09031086+0.j        ]
 [-0.47501097+0.j         -0.42186345+0.22902063j -0.42186345-0.22902063j
   0.75539391+0.j        ]
 [-0.38811411+0.j          0.28981766-0.28690483j  0.28981766+0.28690483j
  -0.2342805 +0.j        ]]


## 2.2. Solving linear systems

A linear system of equations is a set of two or more linear equations sharing the same variables. These linear systems of equations may have infinitely, unique or no solution. A solution of a linear system is an assignment of values to the variables such that each of the equations is satisfied. The set of all possible solutions is called the solution set.

Lets say we have a the following system:

x1 + x2 = 2200 <br>
1.5x1 + 4x2 = 5500


In [139]:
# This system can be rewrited as a matrix equation Ax = b, 
# where A is the matrix of coefficients, x is the vector of unknowns, and b is the vector of constants.

A = np.array([[1, 1], [1.5, 4]])
b = np.array([2200, 5050])

In [144]:
# which solution is x = A^-1 * b. Manually is

manual_solution = np.linalg.inv(A).dot(b) # This calculates the inverse of A and multiplies it by b to get the solution vector x
print("The manual solution is:", manual_solution)

# The manual solution can lead to numerical instability and is not recommended for solving linear systems. 
# Instead, we can use the solve function as follows

prefered_solution = np.linalg.solve(A,b)
print("The preferred solution is:", prefered_solution)

The manual solution is: [1500.  700.]
The preferred solution is: [1500.  700.]


In [148]:
# We can compare the solutions obtained by both methods to see if they are the same.
manual_solution == prefered_solution

array([False, False])

In [150]:
# The comparison above leads to a misunderstanding of the fact that the two solutions are exactly the same. 
# The False conclusion obtained is due to numerical precision issues. Hence, a better way to compare them is 
np.allclose(manual_solution, prefered_solution)

True

# 3. LOADING DATA INTO NUMPY

## 3.1. Loading data using CSVs

A great way to load a large amount of data directly into Numpy is using the *genfromtxt* method

In [158]:
# Automatically determine types and use the first line as column names. 
# Using the a filepath that includes the name of the file and its extension

file_path = r'C:\Users\jober\OneDrive\Desktop\Data_Science\Data Science - Study notes\Data_used\bikes.csv'
data = np.genfromtxt(file_path, delimiter=',', encoding='utf-8', names=True) 

# The data loaded is
data

array([(nan, nan, nan,  993., nan, 11., nan, 15., 73.9, 12.7, nan),
       (nan, nan, nan,  623., nan, 31., nan, 19., 69.1,  6.9, nan),
       (nan, nan, nan, 1040., nan, 15., nan, 23., 73. , 16.1, nan), ...,
       (nan, nan, nan,  824., nan, 31., nan, 20.,  5. , 16.1, nan),
       (nan, nan, nan,  178., nan, 23., nan, 31.,  7. , 11.5, nan),
       (nan, nan, nan,  214., nan, 15., nan, 15., 10.9, 15. , nan)],
      dtype=[('gender', '<f8'), ('starttime', '<f8'), ('stoptime', '<f8'), ('tripduration', '<f8'), ('from_station_name', '<f8'), ('start_capacity', '<f8'), ('to_station_name', '<f8'), ('end_capacity', '<f8'), ('temperature', '<f8'), ('wind_speed', '<f8'), ('events', '<f8')])

In [157]:
# the data is stored in a structured array, where each column can be accessed by its name. 
# For example, to access the "gender" column, we can use:

data['gender']

array([nan, nan, nan, ..., nan, nan, nan])

## Summary
We have explored the core foundations of NumPy, moving from the underlying memory architecture that makes it so fast to hands-on operations with multidimensional arrays, math functions, and data filtering.

Because standard Python lists are designed for general-purpose programming, they struggle with large-scale numerical tasks. NumPy bridges this gap by leveraging C-level optimizations, uniform data types, and contiguous memory allocation. These design choices enable vectorized math, matrix operations, and lightning-fast processing that form the bedrock of the entire Python data science ecosystem—powering downstream libraries like Pandas, SciPy, and TensorFlow.
