# Numerical Python (Numpy)

NumPy (Numerical Python) is a powerful Python library built on C, acting as a wrapper around C functions to leverage its superior execution speed. Numpy improves Python language capabilities to operate with multidimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

Unlike standard Python lists—which are flexible arrays containing pointers to objects scattered in memory—NumPy arrays consist of fixed-type data (such as continuous blocks of 32-bit integers).

This architecture allows NumPy to process operations much faster than Python lists for three key reasons:

- Uniform Data Types: Because all elements share the exact same data type, operations can be executed directly without constant type-checking.

- Reduced Overhead: Standard Python list items must store size, reference counts, object types, and values individually. NumPy's streamlined structure eliminates this overhead, resulting in significantly faster processing and lower memory consumption.

- Contiguous Memory Allocation: NumPy stores its data in continuous blocks right next to each other in memory. In contrast, standard Python lists scatter items across memory, forcing the CPU to waste time jumping back and forth to retrieve them. Continuous memory allows for much faster data access and better utilization of modern CPU caching.

Therefore, we can conclude that *Python Lists* are designed for general-purpose programming and data organization. They support operations like appending, inserting, and removing items easily, but do not support native mathematical operations (e.g., adding two lists together concatenates them rather than adding their elements mathematically), while *NumPy Arrays* are designed specifically for mathematical and numerical computations. They natively support vectorized math, matrix multiplications, linear algebra, statistical operations, and broadcasting.

Other libraries like Tensorflow or Scipy are built on Numpy. It worth the time!

### Content
- Creating arrays
- Methods and important properties
- Modifying the datatype
- Trigonometric functions
- Operating with arrays
- Generating random numbers
- Obtaining statistics 
- Filtering data
- Concatenating arrays
- Selecting data inside arrays

### Creating arrays.
The arrays are the core elements of Numpy. The first step is loading Numpy:

In [2]:
# First install Numpy as pip install numpy
import numpy as np

In [3]:
# list are created as follows
list1 = [1, 2, 3, 4, 5]

In [5]:
# We can create a numpy array from the list already created or directly introducing the values in the array as follows
arr1 =np.array(list1)
arr2 = np.array([30, 21, 8, 14, 5])

In [6]:
#To retreive the array we can use the print function as follows
print(arr1)
print(arr2)

[1 2 3 4 5]
[30 21  8 14  5]


Please notice the difference between lists and arrays when presented 

In [9]:
print("A list is: ", list1, "and a numpy array is: ", arr1)

A list is:  [1, 2, 3, 4, 5] and a numpy array is:  [1 2 3 4 5]


An array may be or higher order (n-dimentional). Hence, These arrays can be created as:

In [12]:
arr_2d = np.array([[24,14,7],[51,3,95]])

arr_2d 

array([[24, 14,  7],
       [51,  3, 95]])

### Methods and important properties
The most basic properties of arrays are

In [16]:
# The shape of an array can be retrieved using the shape attribute as follows
arr_2d.shape 

(2, 3)

Indicates the number of rows and columns in the array. In this case, it is a 2x3 array (2 rows and 3 columns).

In [17]:
# The number of dimensions of an array can be retrieved using the ndim attribute as follows
arr_2d.ndim

2

The dimensions indicates the number of axes or the rank of the array. In the precedent example, 2 dimensions.

In [20]:
# The data type of an array can be retrieved using the dtype attribute as follows
arr_2d.dtype

dtype('int32')

This means integer of 32 bits. The data type indicates the size of memory used in computers memory for each element. 

In [21]:
# The number of elements in and array can be retrieved using the size attribute as follows
arr_2d.size

6